---
title: Fast Forward Labs Blog
timezone: UTC - 5
collections:
  links:
    title: Links
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contact@fastforwardlabs.com
description: 'Fast Forward Labs is a machine intelligence research company. We focus on taking technologies that are just becoming possible, and making them useful.'
baseurl: ''
url: 'http://blog.fastforwardlabs.com'
twitter_username: fastforwardlabs
github_username: fastforwardlabs
markdown: kramdown
paginate: 20
paginate_path: "/page/:num/"
gems:
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
